name: Deploy React Portfolio

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build with Vite
      run: npm run build
      env:
        CI: false
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # Navigate to existing project directory
          cd /srv/app/react/portfolio
          
          # Pull latest changes
          git pull origin main
          
          # Install dependencies and build
          npm ci
          npm run build
          
          # Stop existing container
          docker-compose down
          
          # Rebuild Docker image with new build
          docker build -t portfolio-reactapp .
          
          # Start container
          docker-compose up -d
          
          # Clean up old images
          docker system prune -f
          
          echo "Deployment complete!"
